# Generated by Django 5.1.5 on 2025-01-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desciption',
            new_name='description',
        ),
    ]
